name: dual_v2_2_left_spark2_gripper_right_spark2_gripper
urdf: share/left_spark2_gripper_right_spark2_gripper/dual_arm.urdf
import_yaml: share/config/components/dual_v2_2.yaml
gripper:
  - import_yaml: share/config/components/gripper_left.yaml
  - import_yaml: share/config/components/gripper_right.yaml
