name: gripperL
type: RmdCanGripper
joint_size: 1
urdf_joints: ["gripper_J1_l"]
urdf_links: ["gripper_L1_l", "gripper_L2_l"]
panel_display_joint_names: ["L_gripper"]
offset_from_ee: [0.10, 0, 0]
hardware:
  motor_id: 8
  can_device_index: 0
  can_channel: 0
  open_position_deg: -77.62
  close_position_deg: 5.28
safety:
  joint_soft_limit:
    position: [[0], [1]]
  joint_hard_limit:
    position: [[0], [1]]
